apiVersion: backstage.io/v1alpha1
kind: component
metadata:
  name: skylark-base-project
  description: ${{values.description | dump}}
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: experimental
  owner: ${{values.owner | dump}}